// SPDX-License-Identifier: Apache-2.0

package proxy

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/textproto"
	"strings"
	"sync"
	"time"

	"github.com/luraproject/lura/v2/config"
	"github.com/luraproject/lura/v2/logging"
)

// DefaultRateLimitAPIKeyHeader is the header inspected for the API key when
// the rate limit dimension is apikey and no header is configured
const DefaultRateLimitAPIKeyHeader = "X-Api-Key"

// ErrRateLimited is returned by the rate limit middleware when a request is
// rejected because it exceeds the configured limit
var ErrRateLimited = errors.New("rate limit exceeded")

// RateLimitError is the error returned by the rate limit middleware when a
// request is rejected. It implements the responseError interface used by the
// routers so the client receives a 429 Too Many Requests status code
type RateLimitError struct {
	// Key is the rate limit dimension key that exceeded the limit
	Key string
	// RetryAfter is the suggested time the client should wait before retrying
	RetryAfter time.Duration
}

// Error implements the error interface
func (e RateLimitError) Error() string {
	return fmt.Sprintf("%s for key %q, retry after %s", ErrRateLimited, e.Key, e.RetryAfter)
}

// Unwrap implements the unwrap interface, so errors.Is(err, ErrRateLimited) works
func (e RateLimitError) Unwrap() error { return ErrRateLimited }

// StatusCode implements the responseError interface used by the routers
func (e RateLimitError) StatusCode() int { return http.StatusTooManyRequests }

// Headers implements the headerResponseError interface used by the routers
func (e RateLimitError) Headers() map[string][]string {
	seconds := int(e.RetryAfter.Seconds()) + 1
	return map[string][]string{"Retry-After": {fmt.Sprintf("%d", seconds)}}
}

// IsRateLimitError reports if the received error was generated by the rate
// limit middleware
func IsRateLimitError(err error) bool { return errors.Is(err, ErrRateLimited) }

// Store abstracts the shared state backend used by the rate limiters.
//
// The default implementation is an in-memory store, valid for single
// instance deployments. For distributed deployments, all the instances must
// share the limiter state, so a centralized implementation of this interface
// (e.g. backed by Redis, using INCR/Lua scripts for atomicity) should be
// injected with SetStore before the proxy factory builds the stacks.
type Store interface {
	// AllowTokenBucket consumes one token from the bucket identified by key.
	// The bucket is refilled at rate tokens per second up to burst tokens.
	// It returns if the request is allowed and, when it is not, the time the
	// client should wait before retrying.
	AllowTokenBucket(key string, rate float64, burst int, now time.Time) (bool, time.Duration)
	// AllowSlidingWindow registers a hit in the sliding window identified by
	// key. At most limit hits are allowed per window. It returns if the
	// request is allowed and, when it is not, the time the client should
	// wait before retrying.
	AllowSlidingWindow(key string, limit int, window time.Duration, now time.Time) (bool, time.Duration)
}

var (
	storeMu     sync.RWMutex
	sharedStore Store = NewMemoryStore()
)

// SetStore replaces the shared Store used by the rate limit middlewares.
// Use it to plug a centralized store (e.g. Redis) so the limiter state is
// shared between all the instances of a distributed deployment
func SetStore(s Store) {
	storeMu.Lock()
	sharedStore = s
	storeMu.Unlock()
}

// GetStore returns the shared Store used by the rate limit middlewares
func GetStore() Store {
	storeMu.RLock()
	defer storeMu.RUnlock()
	return sharedStore
}

type bucketState struct {
	tokens   float64
	lastSync time.Time
}

type windowState struct {
	hits []time.Time
}

// MemoryStore is an in-memory Store implementation. It is safe for
// concurrent use but it does not share the state between processes, so it is
// only valid for single instance deployments
type MemoryStore struct {
	mu      sync.Mutex
	buckets map[string]*bucketState
	windows map[string]*windowState
}

// NewMemoryStore returns a new in-memory Store
func NewMemoryStore() *MemoryStore {
	return &MemoryStore{
		buckets: map[string]*bucketState{},
		windows: map[string]*windowState{},
	}
}

// AllowTokenBucket implements the Store interface
func (s *MemoryStore) AllowTokenBucket(key string, rate float64, burst int, now time.Time) (bool, time.Duration) {
	s.mu.Lock()
	defer s.mu.Unlock()

	b, ok := s.buckets[key]
	if !ok {
		b = &bucketState{tokens: float64(burst), lastSync: now}
		s.buckets[key] = b
	}

	b.tokens += now.Sub(b.lastSync).Seconds() * rate
	if capacity := float64(burst); b.tokens > capacity {
		b.tokens = capacity
	}
	b.lastSync = now

	if b.tokens >= 1 {
		b.tokens--
		return true, 0
	}
	return false, time.Duration((1 - b.tokens) / rate * float64(time.Second))
}

// AllowSlidingWindow implements the Store interface
func (s *MemoryStore) AllowSlidingWindow(key string, limit int, window time.Duration, now time.Time) (bool, time.Duration) {
	s.mu.Lock()
	defer s.mu.Unlock()

	w, ok := s.windows[key]
	if !ok {
		w = &windowState{}
		s.windows[key] = w
	}

	cutoff := now.Add(-window)
	valid := w.hits[:0]
	for _, hit := range w.hits {
		if hit.After(cutoff) {
			valid = append(valid, hit)
		}
	}
	w.hits = valid

	if len(w.hits) < limit {
		w.hits = append(w.hits, now)
		return true, 0
	}
	return false, w.hits[0].Add(window).Sub(now)
}

// rateLimitKeyFunc extracts the rate limit dimension key from a request
type rateLimitKeyFunc func(*Request) string

// NewRateLimitMiddlewareWithLogger creates a proxy middleware that rate
// limits the requests to the received backend. When the backend has no rate
// limit configuration enabled, the middleware is a pass-through
func NewRateLimitMiddlewareWithLogger(logger logging.Logger, remote *config.Backend) Middleware {
	if remote.RateLimit == nil || !remote.RateLimit.Enabled {
		return emptyMiddlewareFallback(logger)
	}
	scope := fmt.Sprintf("%s %s -> %s", remote.ParentEndpointMethod, remote.ParentEndpoint, remote.URLPattern)
	return newRateLimitMiddleware(logger, remote.RateLimit, scope)
}

// NewRateLimitMiddleware creates a proxy middleware that rate limits the
// requests to the received backend
func NewRateLimitMiddleware(remote *config.Backend) Middleware {
	return NewRateLimitMiddlewareWithLogger(logging.NoOp, remote)
}

// NewEndpointRateLimitMiddlewareWithLogger creates a proxy middleware that
// rate limits the requests to the received endpoint. When the endpoint has
// no rate limit configuration enabled, the middleware is a pass-through
func NewEndpointRateLimitMiddlewareWithLogger(logger logging.Logger, cfg *config.EndpointConfig) Middleware {
	if cfg.RateLimit == nil || !cfg.RateLimit.Enabled {
		return emptyMiddlewareFallback(logger)
	}
	return newRateLimitMiddleware(logger, cfg.RateLimit, cfg.Method+" "+cfg.Endpoint)
}

func newRateLimitMiddleware(logger logging.Logger, cfg *config.RateLimitConfig, scope string) Middleware {
	rate := cfg.Rate
	if rate <= 0 {
		rate = 1
	}
	burst := cfg.Burst
	if burst <= 0 {
		burst = 1
	}
	// the sliding window holding burst requests at the configured rate
	window := time.Duration(float64(burst) / rate * float64(time.Second))
	keyFunc := rateLimitKeyFuncFor(cfg, scope)

	return func(next ...Proxy) Proxy {
		if len(next) > 1 {
			logger.Fatal(fmt.Sprintf("too many proxies for this %s proxy middleware: NewRateLimitMiddleware only accepts 1 proxy, got %d",
				scope, len(next)))
			return nil
		}

		return func(ctx context.Context, request *Request) (*Response, error) {
			key := scope + "|" + keyFunc(request)
			now := time.Now()

			var allowed bool
			var retryAfter time.Duration
			if cfg.Algorithm == config.RateLimitAlgorithmSlidingWindow {
				allowed, retryAfter = GetStore().AllowSlidingWindow(key, burst, window, now)
			} else {
				allowed, retryAfter = GetStore().AllowTokenBucket(key, rate, burst, now)
			}

			if allowed {
				return next[0](ctx, request)
			}

			err := RateLimitError{Key: key, RetryAfter: retryAfter}
			logger.Warning("[RATE-LIMIT] Request rejected:", err.Error())
			return nil, err
		}
	}
}

func rateLimitKeyFuncFor(cfg *config.RateLimitConfig, scope string) rateLimitKeyFunc {
	switch cfg.Dimension {
	case config.RateLimitDimensionIP:
		return clientIPKey
	case config.RateLimitDimensionAPIKey:
		header := cfg.APIKeyHeader
		if header == "" {
			header = DefaultRateLimitAPIKeyHeader
		}
		header = textproto.CanonicalMIMEHeaderKey(header)
		return func(r *Request) string {
			if key := headerValue(r, header); key != "" {
				return key
			}
			return "anonymous"
		}
	default:
		// all the requests share the same key, so the limit applies to the
		// whole endpoint or backend
		return func(*Request) string { return scope }
	}
}

func clientIPKey(r *Request) string {
	if forwarded := headerValue(r, "X-Forwarded-For"); forwarded != "" {
		return strings.TrimSpace(strings.Split(forwarded, ",")[0])
	}
	if realIP := headerValue(r, "X-Real-Ip"); realIP != "" {
		return realIP
	}
	return "unknown"
}

func headerValue(r *Request, name string) string {
	if r == nil {
		return ""
	}
	if vs, ok := r.Headers[name]; ok && len(vs) > 0 {
		return vs[0]
	}
	// fallback for non-canonical header names
	for k, vs := range r.Headers {
		if len(vs) > 0 && strings.EqualFold(k, name) {
			return vs[0]
		}
	}
	return ""
}
